source 'https://rubygems.org'

gem 'rails', '3.2.8'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'

gem 'slim'
gem "haml-rails"

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  
  gem 'compass'
  gem 'compass-rails'
  gem 'modular-scale'
  gem 'sassy-math'
  gem 'zurb-foundation'
  gem 'foundation-icons-sass-rails'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'libv8', '~> 3.11.8'

gem 'carrierwave'
gem "mini_magick"
gem 'ckeditor'

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
gem 'spree', :path => '..'
gem 'spree_auth_devise', :git => "git://github.com/spree/spree_auth_devise", :branch => 'edge'

gem 'geocoder'
gem 'deface'
gem 'diffy'

gem 'simple_form'
gem 'simple_form_fancy_uploads'
gem 'bootstrap-sass', '~> 2.1.0.1'

gem 'ckeditor'

group :development do
  gem 'rb-inotify', :require => false
  gem 'rb-fsevent', :require => false
  gem 'rb-fchange', :require => false
  gem 'guard'
  gem 'guard-livereload'
  gem 'guard-rspec'
  
  gem 'email_spec', '~> 1.2.1'

  gem 'ffaker'
  gem 'libnotify'
  
  gem 'launchy'

  gem 'seed_dump'
  gem 'quiet_assets'

end

group :test, :development do
  gem 'factory_girl_rails', '~> 1.7.0'
  gem 'selenium-webdriver', '2.25.0'
  gem "rspec-rails", "~> 2.0"
end

group :test do
  gem 'shoulda-matchers'
  gem 'capybara'
  gem 'database_cleaner', '0.7.1'
  gem 'guard-rspec'
end

gem 'select2-rails'

gem 'thin'